INSERT INTO allergies (name)
VALUES ('Arachides'),
       ('Fruits à coque'),
       ('Lait'),
       ('Œufs'),
       ('Blé'),
       ('Soja'),
       ('Poisson'),
       ('Crustacés'),
       ('Sésame'),
       ('Moutarde'),
       ('Gluten'),
       ('Sulfites'),
       ('Lupin'),
       ('Céleri'),
       ('Mollusques'),
       ('Kiwi'),
       ('Banane'),
       ('Pollen'),
       ('Latex'),
       ('Maïs'),
       ('Viande de boeuf'),
       ('Viande de porc'),
       ('Viande de poulet'),
       ('Fraise'),
       ('Chocolat'),
       ('Framboise'),
       ('Tomate'),
       ('Pêche'),
       ('Abricot'),
       ('Ananas'),
       ('Pomme'),
       ('Poire'),
       ('Cacahuète'),
       ('Noix'),
       ('Amande'),
       ('Noisette'),
       ('Pistache'),
       ('Châtaigne'),
       ('Menthe'),
       ('Cannelle'),
       ('Curcuma'),
       ('Coriandre'),
       ('Basilic'),
       ('Oignon'),
       ('Ail'),
       ('Champignon'),
       ('Persil'),
       ('Carotte'),
       ('Pomme de terre'),
       ('Haricot vert'),
       ('Petit pois'),
       ('Chou'),
       ('Poivron'),
       ('Radis'),
       ('Concombre'),
       ('Aubergine'),
       ('Courgette'),
       ('Melon'),
       ('Pastèque'),
       ('Figue'),
       ('Raisin'),
       ('Miel'),
       ('Fromage'),
       ('Yaourt'),
       ('Crème fraîche'),
       ('Beurre'),
       ('Lait de chèvre'),
       ('Lait de brebis'),
       ('Farine de blé'),
       ('Seigle'),
       ('Orge'),
       ('Avoine'),
       ('Épeautre'),
       ('Riz'),
       ('Sarrasin'),
       ('Quinoa'),
       ('Millet'),
       ('Soja fermenté'),
       ('Tofu'),
       ('Sauce soja'),
       ('Lécithine de soja'),
       ('Algues'),
       ('Huîtres'),
       ('Calamar'),
       ('Thon'),
       ('Saumon'),
       ('Crevettes'),
       ('Langouste'),
       ('Crabe'),
       ('Écrevisses'),
       ('Escargots'),
       ('Caviar'),
       ('Viande de cheval'),
       ('Lapin'),
       ('Dinde'),
       ('Canard'),
       ('Oie'),
       ('Foie gras'),
       ('Gélatine'),
       ('Additifs alimentaires'),
       ('Colorants alimentaires'),
       ('Conservateurs');
